trigger:
- main

pool:
  name: Default

steps:
- task: DockerInstaller@0

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'mobinaali/app_mobina'
    command: 'buildAndPush'
    Dockerfile: 'simple-nodejs-app/Dockerfile'
    tags: 'latest'
